<!--[if (lt IE 9) & (!IEMobile)]>
<script type="text/javascript" src="theme/js/lib/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="common/js/lib/jquery.min.js"></script>
<script type="text/javascript" src="theme/js/lib/device.min.js"></script>
<script type="text/javascript" src="theme/js/lib/select2.full.min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.columnizer.js"></script>
<script type="text/javascript" src="theme/js/lib/jquery.dotdotdot.min.js"></script>
<script type="text/javascript" src="theme/js/lib/scrollreveal.min.js"></script>
<script type="text/javascript" src="theme/js/lib/ScrollMagic.min.js"></script>
<script type="text/javascript" src="theme/js/lib/TweenMax.min.js"></script>
<script type="text/javascript" src="theme/js/lib/animation.gsap.min.js"></script>

<!--<script type="text/javascript" src="theme/js/lib/bootstrap-modal.min.js"></script>-->
<script type="text/javascript" src="theme/js/js.js"></script>