<footer id="site-footer" class="site-footer">
  <div class="container">
    <div class="logo"><a href="#"><img src="theme/images/logo-a.png" alt=""></a></div>
    <div class="address">
      <p>Analytical Research Laboratories<br>
        840 Research Parkway, Ste. 546<br>
        Oklahoma City, OK 73104</p>
    </div>
    <div class="tel">
      <p>Toll Free: <a href="tel:8003931595">(800) 393-1595</a> <br>
        Phone: <a href="tel:4052711144">(405) 271-1144</a> Fax: (405) 271-1174<br>
        E-mail: <a href="mailto:info@arlok.com">info@arlok.com</a></p>
    </div>

    <div class="career">
      <span class="ico ss-icon ss-glyphish-outlined ss-briefcase"></span>

      <p>
        Interested in a career with ARL?<br>
        Learn more here or email<br>
        <a href="mailto:info@arlok.com">andhr@arlok.com</a>
      </p>
    </div>
    <div class="text">
      ARL is accredited to the ISO 17025:2005 standard as applicable to our scope of accreditation that outlines general requirements for the competence of testing and calibration laboratories.
    </div>
  </div>
</footer>