<header id="site-header" class="site-header">
  <div class="container">
   <div class="logo">
        <a href="#"><img src="theme/images/logo.png" alt=""></a>
   </div>
    <div class="nav-wrap">
      <div class="nav-inner">
        <nav class="nav">
          <a href="#" class="btn-nav"></a>
          <div class="region region-header-menu">
            <div id="block-menu-block-1" class="block block-menu-block text">


              <div class="content">
                <div class="menu-block-wrapper menu-block-1 menu-name-main-menu parent-mlid-0 menu-level-1">
                  <ul class="menu"><li class="first expanded menu-mlid-605"><a href="/laboratory-services">Laboratory Services</a><ul class="menu"><li class="first last leaf menu-mlid-617 menu-views"><div class="view view-services view-id-services view-display-id-menu view-dom-id-2e461039345360af23be0aaab3dc3d85">



                            <div class="view-content">
                              <div class="item-list">    <ul>          <li class="views-row views-row-1 views-row-odd views-row-first">
                                    <div class="views-field views-field-field-service-icon">        <div class="field-content"><a href="/node/3"><span class="ico"><img src="http://arl.funnelstagingtoo.com/sites/default/files/ico-title-1.png" width="54" height="62" /> </span>
                                          Analytical</a>
                                      </div>  </div></li>
                                  <li class="views-row views-row-2 views-row-even">
                                    <div class="views-field views-field-field-service-icon">        <div class="field-content"><a href="/node/5"><span class="ico"><img src="http://arl.funnelstagingtoo.com/sites/default/files/Service%20Icons/ico-title-2.png" width="62" height="62" /> </span>
                                          Microbiology</a>
                                      </div>  </div></li>
                                  <li class="views-row views-row-3 views-row-odd">
                                    <div class="views-field views-field-field-service-icon">        <div class="field-content"><a href="/node/6"><span class="ico"><img src="http://arl.funnelstagingtoo.com/sites/default/files/Service%20Icons/ico-title-3.png" width="68" height="63" /> </span>
                                          Raw Material Testing</a>
                                      </div>  </div></li>
                                  <li class="views-row views-row-4 views-row-even">
                                    <div class="views-field views-field-field-service-icon">        <div class="field-content"><a href="/node/7"><span class="ico"><img src="http://arl.funnelstagingtoo.com/sites/default/files/Service%20Icons/ico-title-4.png" width="56" height="56" /> </span>
                                          Forensics</a>
                                      </div>  </div></li>
                                  <li class="views-row views-row-5 views-row-odd views-row-last">
                                    <div class="views-field views-field-field-service-icon">        <div class="field-content"><a href="/node/8"><span class="ico"><img src="http://arl.funnelstagingtoo.com/sites/default/files/Service%20Icons/ico-title-5.png" width="48" height="63" /> </span>
                                          Pharmaceuticals</a>
                                      </div>  </div></li>
                                </ul></div>    </div>






                          </div></li>
                      </ul></li>
                    <li class="expanded menu-mlid-606"><a href="/industries/compounding">Industries</a><ul class="menu"><li class="first leaf menu-mlid-666"><a href="/industries/compounding">Compounding</a></li>
                        <li class="leaf menu-mlid-668"><a href="/laboratory-services/forensics-0">Forensics</a></li>
                        <li class="last leaf menu-mlid-667"><a href="/laboratory-services/pharmaceuticals-0">Pharmaceuticals</a></li>
                      </ul></li>
                    <li class="expanded menu-mlid-607"><a href="https://www.arlokapps.com/">Resources</a><ul class="menu"><li class="first leaf menu-mlid-642"><a href="https://www.arlokapps.com/">ARLOKAPPS</a></li>
                        <li class="leaf menu-mlid-649"><a href="/arl-forms">Forms</a></li>
                        <li class="leaf menu-mlid-650"><a href="/request-quote">Request a quote</a></li>
                        <li class="leaf menu-mlid-647"><a href="/articles">Articles</a></li>
                        <li class="last leaf menu-mlid-660"><a href="/association">Associations</a></li>
                      </ul></li>
                    <li class="last expanded menu-mlid-608"><a href="/quality-accreditation">About Us</a><ul class="menu"><li class="first leaf menu-mlid-644"><a href="/quality-accreditation">Accreditation</a></li>
                        <li class="leaf menu-mlid-651"><a href="/facilities-laboratories">Facilities / Laboratories</a></li>
                        <li class="leaf menu-mlid-625"><a href="/staff">Staff</a></li>
                        <li class="leaf menu-mlid-665"><a href="/news">News</a></li>
                        <li class="leaf menu-mlid-677"><a href="/careers">Careers</a></li>
                        <li class="last leaf menu-mlid-676"><a href="/contact-us">Contact Us</a></li>
                      </ul></li>
                  </ul></div>
              </div>
            </div>
          </div>
        </nav>
        <div class="region region-header">
          <div id="block-arl-custom-arl-custom-user-info" class="block block-arl-custom user-info">


            <div class="content">
              <a href="https://www.arlokapps.com/" class="status btn" target="_blank">Client Log in</a>  </div>
          </div>
        </div>
        <a class="btn-search" href="#"></a>
        <div class="search-wrap">
          <div class="form form-search">
            <div class="form-item">
              <input type="text" class="form-text" placeholder="HIT ENTER TO SEARCH"/>
            </div>
            <div class="form-actions">
              <input type="submit" class="form-submit"/>
            </div>
          </div>
          <a class="btn-close" href="#"></a>
        </div>
      </div>
    </div>
<!--   <div class="nav-wrap">-->
<!--     <div class="nav-inner">-->
<!--      <nav class="nav">-->
<!--        <a href="#" class="btn-nav"></a>-->
<!---->
<!--        <div class="menu-block-wrapper">-->
<!--          <ul class="menu">-->
<!--          <li class="expanded active"><a href="#">Laboratory Services</a>-->
<!--            <ul class="menu">-->
<!--              <li>-->
<!--                <div>-->
<!--                  <ul>-->
<!--                    <li>-->
<!---->
<!--                      <div>-->
<!--                        <a href="#">-->
<!--                          <span class="ico"><img src="theme/images/tmp/header-ico-1.png" alt=""></span>-->
<!--                          Analytical-->
<!--                        </a>-->
<!--                      </div>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                      <div>-->
<!--                        <a href="#">-->
<!--                          <span class="ico"><img src="theme/images/tmp/header-ico-2.png" alt=""></span>-->
<!--                          Microbiological-->
<!--                        </a>-->
<!--                      </div>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                      <div>-->
<!--                        <a href="#">-->
<!--                          <span class="ico"><img src="theme/images/tmp/header-ico-3.png" alt=""></span>-->
<!--                          Compendial-->
<!--                        </a>-->
<!--                      </div>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                      <div>-->
<!--                        <a href="#">-->
<!--                          <span class="ico"><img src="theme/images/tmp/header-ico-4.png" alt=""></span>-->
<!--                          Forensics-->
<!--                        </a>-->
<!--                      </div>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                      <div>-->
<!--                        <a href="#">-->
<!--                          <span class="ico"><img src="theme/images/tmp/header-ico-5.png" alt=""></span>-->
<!--                          Research &-->
<!--                          Development-->
<!--                        </a>-->
<!--                      </div>-->
<!--                    </li>-->
<!--                  </ul>-->
<!--                </div>-->
<!--              </li>-->
<!--            </ul>-->
<!--          </li>-->
<!--          <li class="expanded">-->
<!--            <a href="#">Industries</a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a href="#">Resources</a>-->
<!--          </li>-->
<!--          <li class="expanded">-->
<!--            <a href="#">About Us</a>-->
<!---->
<!--          </li>-->
<!--        </ul>-->
<!--        </div>-->
<!--      </nav>-->
<!--      <a href="#" class="btn status">CLIENT LOG IN</a>-->
<!--     </div>-->
<!--    </div>-->
  </div>
</header>